apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: result
    tier: frontend
    autor: FabiOctopus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
      tier: frontend
      autor: FabiOctopus
  template:
    metadata:
      labels:
        app: result
        tier: frontend
        autor: FabiOctopus
    spec:
      containers:
      - name: result
        image: harbor.101si.ar/pin/voting_result:VAR_RESULT_VERSION
        ports:
        - containerPort: 80
