apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    app: vote
    tier: frontend
    autor: FabiOctopus  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
      tier: frontend
      autor: FabiOctopus
  template:
    metadata:
      labels:
        app: vote
        tier: frontend
        autor: FabiOctopus  
    spec:
      containers:
      - name: vote
        image: harbor.101si.ar/pin/voting_vote:VAR_VOTE_VERSION
        ports:
        - containerPort: 80
