apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
    autor: FabiOctopus  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
      autor: FabiOctopus  
  template:
    metadata:
      labels:
        app: worker
        autor: FabiOctopus  
    spec:
      containers:
      - name: worker
        image: harbor.101si.ar/pin/voting_worker:VAR_WORKER_VERSION