apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
    tier: backend
    autor: FabiOctopus
  name: db
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
  selector:
    app: db
    tier: backend
    autor: FabiOctopus