apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result
    tier: frontend
    autor: FabiOctopus
spec:
  type: NodePort
  selector:
    app: result
    tier: frontend
    autor: FabiOctopus
  ports:  
    - port: 5001
      targetPort: 80
      nodePort: 31001
