apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: vote
    tier: frontend
    autor: FabiOctopus
spec:
  type: NodePort
  selector:
    app: vote
    tier: frontend
    autor: FabiOctopus
  ports:
    - port: 5000
      targetPort: 80
      nodePort: 31000
